stages:
  - build
  - test

variables:
  OBJECT_DIR: "obj"
  BIN_DIR: "bin"

cache:
  paths:
    - .nuget/packages/
    - ${OBJECT_DIR}/
    - ${BIN_DIR}/

before_script:
  - 'dotnet restore src/BankApp.Tests/BankApp.Tests.csproj'

build:
  stage: build
  script:
    - 'dotnet build src/BankApp.Tests/BankApp.Tests.csproj --no-restore'

test:
  stage: test
  script:
    - 'dotnet test src/BankApp.Tests/BankApp.Tests.csproj --no-build --verbosity normal'
