stages:
  - test
  - build

variables:
  OBJECT_DIR: "obj"
  BIN_DIR: "bin"

cache:
  paths:
    - .nuget/packages/
    - ${OBJECT_DIR}/
    - ${BIN_DIR}/

before_script:
  - 'dotnet restore BankaBenim.sln'

test_job:
  stage: test
  script:
    - 'dotnet test src/BankApp.Tests/BankApp.Tests.csproj --verbosity normal'

build_job:
  stage: build
  script:
    - 'dotnet build src/BankApp.UI/BankApp.UI.csproj -c Release --no-restore'
  needs:
    - test_job
